import os
from typing import List, Tuple, Optional
from PIL import Image
from google import genai
from google.genai import types
from dotenv import load_dotenv
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

load_dotenv()

def get_client():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
         # In MCP, we might want to return a helpful error so the user knows they need an API key
         raise ValueError("GEMINI_API_KEY not found. Please set it in your Claude Desktop configuration or environment.")
    return genai.Client(api_key=api_key)

def generate_edited_slide(
    target_image: Image.Image,
    style_reference_images: List[Image.Image],
    full_text_context: str,
    user_prompt: str,
    resolution: str = "4K"
) -> Tuple[Image.Image, Optional[str]]:
    """
    Edits an existing slide image based on a prompt and context.
    
    Args:
        target_image: The original slide image to edit.
        style_reference_images: Images to use as style references.
        full_text_context: Text extracted from the PDF for context.
        user_prompt: The AI instructions for editing.
        resolution: Output image resolution.
        
    Returns:
        A tuple of (generated_image, model_response_text).
    """
    client = get_client()

    prompt_parts = []
    prompt_parts.append(user_prompt)
    prompt_parts.append(target_image)

    if style_reference_images:
        prompt_parts.append("Match the visual style (fonts, colors, layout) of these reference images:")
        for img in style_reference_images:
            prompt_parts.append(img)

    if full_text_context:
        prompt_parts.append(f"DOCUMENT CONTEXT:\n{full_text_context}\n")

    config = types.GenerateContentConfig(
        response_modalities=['TEXT', 'IMAGE'],
        image_config=types.ImageConfig(
            image_size=resolution
        )
    )

    try:
        response = client.models.generate_content(
            model='gemini-3-pro-image-preview',
            contents=prompt_parts,
            config=config
        )
    except Exception as e:
        logger.error(f"Gemini API Error: {e}")
        raise RuntimeError(f"Gemini API Error: {e}")

    generated_image = None
    response_text = None
    
    if response.candidates and response.candidates[0].content.parts:
        for part in response.candidates[0].content.parts:
            if part.inline_data:
                from io import BytesIO
                generated_image = Image.open(BytesIO(part.inline_data.data))
            elif part.text:
                response_text = part.text

    if not generated_image:
        raise RuntimeError("No image generated by the model.")

    return generated_image, response_text

def generate_new_slide(
    style_reference_images: List[Image.Image],
    user_prompt: str,
    full_text_context: str = "",
    resolution: str = "4K"
) -> Tuple[Image.Image, Optional[str]]:
    """
    Generates a completely new slide image.
    
    Args:
        style_reference_images: Images to use as style references.
        user_prompt: The AI instructions for generation.
        full_text_context: Text extracted from the PDF for context.
        resolution: Output image resolution.
        
    Returns:
        A tuple of (generated_image, model_response_text).
    """
    client = get_client()

    prompt_parts = []
    prompt_parts.append(user_prompt)

    if style_reference_images:
        prompt_parts.append("Match the visual style (fonts, colors, layout) of these reference images:")
        for img in style_reference_images:
            prompt_parts.append(img)

    if full_text_context:
        prompt_parts.append(f"DOCUMENT CONTEXT:\n{full_text_context}\n")

    config = types.GenerateContentConfig(
        response_modalities=['TEXT', 'IMAGE'],
        image_config=types.ImageConfig(
            image_size=resolution
        )
    )

    try:
        response = client.models.generate_content(
            model='gemini-3-pro-image-preview',
            contents=prompt_parts,
            config=config
        )
    except Exception as e:
        logger.error(f"Gemini API Error: {e}")
        raise RuntimeError(f"Gemini API Error: {e}")

    generated_image = None
    response_text = None
    if response.candidates and response.candidates[0].content.parts:
        for part in response.candidates[0].content.parts:
            if part.inline_data:
                from io import BytesIO
                generated_image = Image.open(BytesIO(part.inline_data.data))
            elif part.text:
                response_text = part.text

    if not generated_image:
        raise RuntimeError("No image generated by the model.")

    return generated_image, response_text
